### ISSUE TITLE
Azure/go-amqp breaking change - Accept renamed to AcceptMessage

### ISSUE THREAD

**Issue by alexg-axis** [amenzhinsky/iothub#53]
The `Accept` method of `Azure/go-amqp` has been renamed to `AcceptMessage` in v0.16.1. Commit where it happened: https://github.com/Azure/go-amqp/commit/760a290f7ceae6bc89047f27dbf48c51a6860134.

Issue that is raised when installing `iothub` when already having a newer version of `Azure/go-amqp` installed:

```
# github.com/amenzhinsky/iothub/eventhub
github.com/amenzhinsky/iothub@v0.7.0/eventhub/client.go:266:15: msg.Accept undefined (type *amqp.Message has no field or method Accept)
```

**Comment by amenzhinsky** [comment]
Thank you for the head-up what's going to change.

Are you using the obsolete way to install golang binaries using GOPATH? Because the project is bound to exact library versions in `go.mod` and currently uses `github.com/Azure/go-amqp v0.13.4`.

https://github.com/amenzhinsky/iothub/blob/master/go.mod#L6

**Comment by alexg-axis** [comment]
No, but turns out I had the wrong version specified for the go-amqp dependency due to an unrelated issue, so it installs just fine now. Thanks for the quick response.
