### ISSUE TITLE
Error 'x509: certificate signed by unknown authority' when using connectionstring

### ISSUE THREAD

**Issue by zambranohally** [amenzhinsky/iothub#79]
I am using this code.
```
iotClient, err := iotdevice.NewFromConnectionString(mqtt.New(), connString)
if err != nil {
     fmt.Println(err.Error())
}
```
I got this error
`network Error : x509: certificate signed by unknown authority`

**Comment by andersonprante** [comment]
Here too!

**Comment by andersonprante** [comment]
The solution is already in the master branch, but because the last tag of package is v0.9.0, go get retrieves the "old version" (latest tag) 

For me, the solution was to run `go get github.com/amenzhinsky/iothub@master`, an then the problem was resolved.

To verify, open `common/tls.go` and check if line 20 contains `// DigiCert Global Root G2 (sha1 fingerprint=df3c24f9bfd666761b268073fe06d1cc8d4f82a4)`

Cheers!

**Comment by amenzhinsky** [comment]
Created `v0.9.1` tag.
